# This file was generated by GoReleaser. DO NOT EDIT.
class Metamate < Formula
  desc ""
  homepage "https://metamate.io"
  version "0.0.59"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/metamatex/metamate/releases/download/v0.0.59/metamate_0.0.59_darwin_amd64.tar.gz"
    sha256 "8b5464d0ca8e313e90a465cf7831d2f3348f70bf88ef475327cb8bfb0ca52ac4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/metamatex/metamate/releases/download/v0.0.59/metamate_0.0.59_linux_amd64.tar.gz"
      sha256 "39b91730ca20674c1071608502115e208673e1d613691e55cc7b6b3edc43146a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metamatex/metamate/releases/download/v0.0.59/metamate_0.0.59_linux_arm64.tar.gz"
        sha256 "b520c3171242904814d139b89e1f7e73fd4098f2614c5e9dad26759d744c7db1"
      else
        url "https://github.com/metamatex/metamate/releases/download/v0.0.59/metamate_0.0.59_linux_armv6.tar.gz"
        sha256 "e8c64213f81df5ee9fd1c560b00ec4133ea4cb5040bef45fe4583bc08ddcb6fe"
      end
    end
  end

  def install
    bin.install "metamate"
  end
end
